[project]
name = "python-notes"
version = "0.1.0"
description = "Notes of Python programming"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["numpy", "pandas", "plotnine", "notebook"]
